### ISSUE TITLE
AT+CIPSSLSIZE <size> range is not enough for big server certificates

### ISSUE THREAD

**Issue by jafontian** [espressif/ESP8266_NONOS_SDK#116]
After set size to 4096 , the maximum size this order can accept.
I try to connect https://www.baidu.com,  and it fails.
After using wireshark to analyze data exchanged between esp8266 and baidu server ,  I realize that handshake protocol certificate package sent by server is 4760 bytes.  and I adjust 4096 to 6144, not by send AT order, just modify source code in libary, it works.
so should size range in AT+CIPSSLSIZE be enlarged?

**Comment by FayeY** [comment]
Hi, it is due to the memory limitation, so that the AT+CIPSSLSIZE has been limited to 4096. 
The official AT firmware needs to make sure that the memory is enough for all its functions, so the SSL buffer has been limited to 4096.
But for your specific application, I believe it should be only a part of functions you used in your application. In this case, you can enlarge the SSL buffer for your own use case. 
Thanks.
