### ISSUE TITLE
wifi_station_get_connect_status() returns 255 

### ISSUE THREAD

**Issue by uzi18** [espressif/ESP8266_NONOS_SDK#153]
Hi all!
Have wifi in AP mode but status returns undocumented value, cant't connect to this AP.
Please explain what does it mean if wifi_station_get_connect_status() returns 255 ?
It is not documented anywhere.
I use SDK 2.0.0 

@wujiangang @FayeY please help me :)

**Comment by xcguang** [comment]
Hi @uzi18 ,
If wifi mode is SOFTAP_MODE or NULL_MODE, or the connect is not established, the value wifi_station_get_connect_status() returns is 0xff.

**Comment by xcguang** [comment]
Hi @uzi18 ,
Can this issue be closed? @FayeY

**Comment by FayeY** [comment]
Closing as this question appears to be answered, please feel free to reopen if this is still an issue. Thanks.

**Comment by uzi18** [comment]
ok thanks for info, please add this value to SDK :)

**Comment by kriegste** [comment]
Stuff like this should be closed only after being properly documented in the pdf.

**Comment by Inq720** [comment]
Oldie, but a goodie...  
In my code, I double checked my mode and status because of thread using this statement...
    os_printf("connect - mode=%u, status=%u\n", wifi_get_opmode(), wifi_station_get_connect_status());
...and got this...
   connect - mode=3, status=255

I'm on SDK version: 2.1.0(7106d38).  I'm a long time developer using the Arduino version, but new (3 days) to this native development using VSCode/PlatformIO and I haven't figured out how to upgrade it to a newer one.
